---
abstract: 'Perl extension for sweet application framework.'
author:
  - 'Kunihiko Miyanaga, <miyanaga@ideamans.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Docs
no_index:
  directory:
    - inc
    - t
requires:
  Filter::Util::Call: 0
  perl: 5.12.4
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
