languages:
    en:
        local_label: English
        global_label: English
    ja:
        local_label: 日本語
        global_label: Japanese
preferred_language: en
ui:
    theme: bootstrap
    bootstrap:
        global_nav_limit: 3
    helper_methods:
        core.link_to_node:
            method: link_to_node
            code: Docs::HelperMethod::Node::link_to_node
        core.link_to_tag:
            method: link_to_tag
            code: Docs::HelperMethod::Node::link_to_tag
        core.bootstrap.icon:
            theme: bootstrap
            method: theme_icon
            code: Docs::HelperMethod::Common::bootstrap_icon
        core.format_datetime:
            method: format_datetime
            code: Docs::HelperMethod::Common::format_datetime
macro_methods:
    core.node:
        tag: node
        type: function
        code: Docs::MacroMethod::Node::node
    core.tag:
        tag: tag
        type: function
        code: Docs::MacroMethod::Node::tag
    core.lang:
        tag: lang
        type: block
        code: Docs::MacroMethod::Common::lang
    core.table:
        tag: table
        type: block
        code: Docs::MacroMethod::Common::table
formatters:
    html:
        label: Plain HTML
        class: Docs::Formatter
    md:
        label: Markdown
        class: Docs::Formatter::Markdown
books:
    root: private/books
search:
    per_page: 10
    quick_per_page: 10
context_methods:
    core.node.url:
        package: Docs::Model::Node
        method: url
        code: Docs::ContextMethod::Node::url
    core.node.hidden:
        package: Docs::Model::Node
        method: hidden
        code: Docs::ContextMethod::Node::hidden
    core.node.children:
        package: Docs::Model::Node
        method: children
        code: Docs::ContextMethod::Node::children
    core.node.number:
        package: Docs::Model::Node
        method: number
        code: Docs::ContextMethod::Node::number
    core.node.numbering:
        package: Docs::Model::Node
        method: numbering
        code: Docs::ContextMethod::Node::numbering
    core.node.updated_on:
        package: Docs::Model::Node
        method: updated_on
        code: Docs::ContextMethod::Node::updated_on
    core.node.title:
        package: Docs::Model::Node
        method: title
        code: Docs::ContextMethod::Node::title
    core.node.lead:
        package: Docs::Model::Node
        method: lead
        code: Docs::ContextMethod::Node::lead
    core.node.plain_lead:
        package: Docs::Model::Node
        method: plain_lead
        code: Docs::ContextMethod::Node::plain_lead
    code.node.first_paragraph:
        package: Docs::Model::Node
        method: first_paragraph
        code: Docs::ContextMethod::Node::first_paragraph
    code.node.excerpt:
        package: Docs::Model::Node
        method: excerpt
        code: Docs::ContextMethod::Node::excerpt
    core.node.body:
        package: Docs::Model::Node
        method: body
        code: Docs::ContextMethod::Node::body
    core.node.html:
        package: Docs::Model::Node
        method: html
        code: Docs::ContextMethod::Node::html
    core.node.body_without_lead:
        package: Docs::Model::Node
        method: body_without_lead
        code: Docs::ContextMethod::Node::body_without_lead
    core.node.plain_text:
        package: Docs::Model::Node
        method: plain_text
        code: Docs::ContextMethod::Node::plain_text
    core.node.plain_text_without_headlines:
        package: Docs::Model::Node
        method: plain_text_without_headlines
        code: Docs::ContextMethod::Node::plain_text_without_headlines
    core.node.author:
        package: Docs::Model::Node
        method: author
        code: Docs::ContextMethod::Node::author
    core.node.author_name:
        package: Docs::Model::Node
        method: author_name
        code: Docs::ContextMethod::Node::author_name
    core.node.author_email:
        package: Docs::Model::Node
        method: author_email
        code: Docs::ContextMethod::Node::author_email
    core.node.author_email_serial:
        package: Docs::Model::Node
        method: author_email_serial
        code: Docs::ContextMethod::Node::author_email_serial
    core.node.headlines:
        package: Docs::Model::Node
        method: headlines
        code: Docs::ContextMethod::Node::headlines
    core.node.raw_tags:
        package: Docs::Model::Node
        method: raw_tags
        code: Docs::ContextMethod::Node::raw_tags
    core.node.tags:
        package: Docs::Model::Node
        method: tags
        code: Docs::ContextMethod::Node::tags
    core.node.tags_include_body:
        package: Docs::Model::Node
        method: tags_include_body
        code: Docs::ContextMethod::Node::tags_include_body
    core.node.normalize:
        package: Docs::Model::Node
        method: normalize
        code: Docs::ContextMethod::Node::normalize
    core.node.date_format:
        package: Docs::Model::Node
        method: date_format
        code: Docs::ContextMethod::Node::date_format
    core.node.datetime_format:
        package: Docs::Model::Node
        method: datetime_format
        code: Docs::ContextMethod::Node::datetime_format
    core.node.format_epoch:
        package: Docs::Model::Node
        method: format_epoch
        code: Docs::ContextMethod::Node::format_epoch
    core.node.copyright:
        package: Docs::Model::Node
        method: copyright
        code: Docs::ContextMethod::Node::copyright
    core.node.seealso:
        package: Docs::Model::Node
        method: seealso
        code: Docs::ContextMethod::Node::seealso
    core.node.next:
        package: Docs::Model::Node
        method: next
        code: Docs::ContextMethod::Node::next
    core.node.prev:
        package: Docs::Model::Node
        method: prev
        code: Docs::ContextMethod::Node::prev
    core.node.flat_next:
        package: Docs::Model::Node
        method: flat_next
        code: Docs::ContextMethod::Node::flat_next
    core.node.glossary:
        package: Docs::Model::Node
        method: glossary
        code: Docs::ContextMethod::Node::glossary
