id: GroongaSearch
groonga:
    root: data/groonga
context_methods:
    groonga.book.path:
        package: Docs::Model::Node::Book
        method: groonga_path
        code: Docs::Component::GroongaSearch::ContextMethod::groonga_path
    groonga.book.console:
        package: Docs::Model::Node::Book
        method: groonga_console
        code: Docs::Component::GroongaSearch::ContextMethod::groonga_console
    groonga.book.migrate:
        package: Docs::Model::Node::Book
        method: groonga_migrate
        code: Docs::Component::GroongaSearch::ContextMethod::groonga_migrate
    groonga.node.groonga_step_paths:
        package: Docs::Model::Node
        method: groonga_step_paths
        code: Docs::Component::GroongaSearch::ContextMethod::groonga_step_paths
    groonga.node.load:
        package: Docs::Model::Node
        method: groonga_load
        code: Docs::Component::GroongaSearch::ContextMethod::groonga_load
    groonga.node.search:
        package: Docs::Model::Node
        method: groonga_search
        code: Docs::Component::GroongaSearch::ContextMethod::groonga_search
    groonga.node.tagsearch:
        package: Docs::Model::Node
        method: groonga_tagsearch
        code: Docs::Component::GroongaSearch::ContextMethod::groonga_tagsearch
commands:
    search:
        handler: Docs::Component::GroongaSearch::Handler::Search
    tagsearch:
        handler: Docs::Component::GroongaSearch::Handler::TagSearch
    quicksearch:
        handler: Docs::Component::GroongaSearch::Handler::QuickSearch
callbacks:
    post_init:
        priority: 5
        code: Docs::Component::GroongaSearch::on_post_init
    node.document.rebuild:
        priority: 8
        code: Docs::Component::GroongaSearch::on_document_rebuild
